# 保存间隔, 单位刻 (1秒=20刻)
# 玩家下线时会保存一次
# 上线后每隔{duration}刻就会保存一次
# 保存位置在 插件文件夹/玩家UUID/时间戳.yml
# 重载后进入的玩家保存间隔改变
duration: 216000

# 备份保留时长, 单位小时
keep: 72

# 检查超时间隔, 单位小时
# 重载无效
check: 3

# 若启用则在玩家死亡时创建一次备份
on_death: false